# Generated by Django 3.0.4 on 2020-03-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='contact',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
