# Generated by Django 3.0.4 on 2020-03-22 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_auto_20200322_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.City', verbose_name='Select City'),
        ),
    ]
