# Generated by Django 3.0.4 on 2020-03-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0007_auto_20200322_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Owner.City', verbose_name='Select City'),
        ),
    ]
