# Generated by Django 3.0.4 on 2020-03-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_product_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Temp', verbose_name='Temp =====')),
            ],
            options={
                'verbose_name': 'img',
                'verbose_name_plural': 'imgs',
            },
        ),
    ]
