# Generated by Django 3.0.4 on 2020-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0009_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img',
        ),
    ]
