# Generated by Django 3.0.4 on 2020-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0011_auto_20200401_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appointment_status',
            field=models.BooleanField(default=False, verbose_name='Count Apointment'),
        ),
    ]
