# Generated by Django 3.0.4 on 2020-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0012_product_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='appointment_status',
        ),
        migrations.AddField(
            model_name='product',
            name='appointment_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Count Apointment'),
        ),
    ]
