# Generated by Django 3.0.4 on 2020-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0013_auto_20200406_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='appointment_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Count Apointment'),
        ),
    ]
