# Generated by Django 3.0.4 on 2020-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0014_auto_20200407_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
