# Generated by Django 3.0.4 on 2020-04-11 18:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0015_auto_20200407_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
