# Generated by Django 3.0.4 on 2020-04-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0016_auto_20200412_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Count For Appointment'),
        ),
    ]
