# Generated by Django 3.0.4 on 2020-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0017_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
