# Generated by Django 3.0.4 on 2020-03-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_auto_20200322_1235'),
        ('Customer', '0002_auto_20200322_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='block_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.City', verbose_name='Select City'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
