# Generated by Django 3.0.4 on 2020-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_auto_20200322_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Enter Appointment Date'),
        ),
    ]
