# Generated by Django 3.0.4 on 2020-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_auto_20200323_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Enter Appointment Date'),
        ),
    ]
