# Generated by Django 3.0.4 on 2020-03-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_auto_20200323_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name=''),
        ),
    ]
