# Generated by Django 3.0.4 on 2020-03-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_appointment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
    ]
