# Generated by Django 3.0.4 on 2020-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_remove_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Enter Appointment Date'),
        ),
    ]
