# Generated by Django 3.0.4 on 2020-03-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_auto_20200325_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Order Is New or Old'),
        ),
    ]
