# Generated by Django 3.0.4 on 2020-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_appointment_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='new',
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(blank=True, choices=[(0, 'aftrer One Day'), (1, 'After two Day'), (2, 'After Three Day'), (2, 'After Four Day'), (2, 'After Five Day')], max_length=1, null=True),
        ),
    ]
