# Generated by Django 3.0.4 on 2020-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_auto_20200331_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calender',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Enter Phone No. :-'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[(0, 'Aftrer One Day'), (1, 'After two Day'), (2, 'After Three Day'), (3, 'After Four Day'), (4, 'After Five Day')], max_length=1),
        ),
    ]
