# Generated by Django 3.0.4 on 2020-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_auto_20200401_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Enter First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to='user', verbose_name='Insert Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Enter Last Name'),
        ),
    ]
