# Generated by Django 3.0.4 on 2020-04-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_auto_20200401_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='advance_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Advance Pay'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='advance_pay_s',
            field=models.BooleanField(default=False, verbose_name='Advance Pay Status'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='c_status',
            field=models.BooleanField(default=False, verbose_name='Conformed ?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_amount',
            field=models.PositiveIntegerField(default=False, verbose_name='Last Pay'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_pay_s',
            field=models.BooleanField(default=False, verbose_name='Advance Pay Status'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Final Amount'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(max_length=150, verbose_name='Trasiction ID')),
                ('TXNAMOUNT', models.FloatField(default=0, verbose_name='Transicton Amount')),
                ('PAYMENTMODE', models.CharField(default='', max_length=50, verbose_name='Payment Mode')),
                ('CURRENCY', models.CharField(default='', max_length=50, verbose_name='Currency of payment mode')),
                ('STATUS', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('GATEWAYMODE', models.CharField(default='', max_length=50, verbose_name='Gateway Mode')),
                ('BANKTXNID', models.CharField(default='', max_length=50, verbose_name='Bank ID')),
                ('BANKNAME', models.CharField(default='', max_length=50, verbose_name='Bank Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Appointment', verbose_name='Appointment ID')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
