# Generated by Django 3.0.4 on 2020-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_auto_20200409_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Complete?'),
        ),
    ]
