# Generated by Django 3.0.4 on 2020-04-11 08:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0015_auto_20200407_2003'),
        ('Customer', '0019_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='feedback_status',
            field=models.BooleanField(default=False, verbose_name='Feedback Sataus'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', ckeditor_uploader.fields.RichTextUploadingField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.Product', verbose_name='Select Product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Profile', verbose_name='Select Customer')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
