# Generated by Django 3.0.4 on 2020-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_auto_20200411_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject???'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reject_resion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Reject Resion'),
        ),
    ]
