# Generated by Django 3.0.4 on 2020-03-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20200321_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
