# Generated by Django 3.0.4 on 2020-03-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0010_appointment_amount'),
        ('Owner', '0008_product_city'),
        ('Employee', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.Appointment', verbose_name='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.Employee', verbose_name='')),
            ],
            options={
                'verbose_name': 'ManageAppointment',
                'verbose_name_plural': 'ManageAppointments',
            },
        ),
        migrations.CreateModel(
            name='Conform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='')),
                ('file', models.FileField(blank=True, null=True, upload_to='conform', verbose_name='')),
                ('date', models.DateField(auto_now_add=True)),
                ('manageAppointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.ManageAppointment', verbose_name='')),
            ],
            options={
                'verbose_name': 'Conform',
                'verbose_name_plural': 'Conforms',
            },
        ),
    ]
