# Generated by Django 3.0.4 on 2020-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_conform_manageappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageappointment',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Conformed?'),
        ),
    ]
