# Generated by Django 3.0.4 on 2020-04-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_payment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paied_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Paied Amount:-'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='BANKNAME',
            field=models.CharField(default='', max_length=50, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='BANKTXNID',
            field=models.CharField(default='', max_length=50, verbose_name='Bank ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='CURRENCY',
            field=models.CharField(default='', max_length=50, verbose_name='Currency of payment mode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='GATEWAYMODE',
            field=models.CharField(default='', max_length=50, verbose_name='Gateway Mode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='PAYMENTMODE',
            field=models.CharField(default='', max_length=50, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TXNAMOUNT',
            field=models.FloatField(default=0, verbose_name='Transicton Amount'),
        ),
    ]
