# Generated by Django 3.0.4 on 2020-04-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20200405_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.AlterField(
            model_name='conform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='conform', verbose_name='Drop File'),
        ),
        migrations.AlterField(
            model_name='conform',
            name='manageAppointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.ManageAppointment', verbose_name='Select Appointment'),
        ),
        migrations.AlterField(
            model_name='conform',
            name='note',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Enter Note'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
