# Generated by Django 3.0.4 on 2020-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_auto_20200409_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageappointment',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject?'),
        ),
    ]
